export const invalidReportJson = {
  files: [undefined, null],
  issues: [
    // JSON stringification of undefined values results in the
    // keys associated with them being removed from the output
    {
      file: "file1.ts",
      dependencies: undefined,
      devDependencies: undefined,
      optionalPeerDependencies: undefined,
      unlisted: undefined,
      binaries: undefined,
      unresolved: undefined,
      exports: undefined,
      types: undefined,
      enumMembers: undefined,
      classMembers: undefined,
      duplicates: undefined,
    },
    // `null` is a valid JSON value
    {
      file: "file2.ts",
      dependencies: null,
      devDependencies: null,
      optionalPeerDependencies: null,
      unlisted: null,
      binaries: null,
      unresolved: null,
      exports: null,
      types: null,
      enumMembers: null,
      classMembers: null,
      duplicates: null,
    },
  ],
};

export const reportJson = {
  files: ["PolarisGalaxy.ts", "Savali.ts", "PocketDimension.tsx"],
  issues: [
    // dependencies
    {
      file: "packages/a/package.json",
      dependencies: [{ name: "react" }, { name: "react-dom" }],
      devDependencies: [{ name: "dotenv" }, { name: "eslint-plugin-jest-dom" }],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {},
      classMembers: {},
      duplicates: [],
    },
    // devDependencies
    {
      file: "packages/b/package.json",
      dependencies: [],
      devDependencies: [{ name: "dotenv" }, { name: "eslint-plugin-jest-dom" }],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {},
      classMembers: {},
      duplicates: [],
    },
    // optionalPeerDependencies
    {
      file: "packages/c/package.json",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [{ name: "dotenv" }],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {},
      classMembers: {},
      duplicates: [],
    },
    // dependencies, devDependencies, and optionalPeerDependencies
    {
      file: "packages/d/package.json",
      dependencies: [{ name: "react" }],
      devDependencies: [{ name: "dotenv" }],
      optionalPeerDependencies: [{ name: "@mui/material" }],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {},
      classMembers: {},
      duplicates: [],
    },
    // unlisted
    {
      file: ".eslintrc.cjs",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [{ name: "@emotion/eslint-plugin" }, { name: "eslint-plugin-jest-dom" }],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {},
      classMembers: {},
      duplicates: [],
    },
    // binaries
    {
      file: "packages/e/package.json",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [{ name: "apollo" }],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {},
      classMembers: {},
      duplicates: [],
    },
    // unresolved
    {
      file: "jest.config.js",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [
        {
          name: "packages/a/src/setupTests.ts",
        },
        {
          name: "packages/a/../b/src",
        },
      ],
      exports: [],
      types: [],
      enumMembers: {},
      classMembers: {},
      duplicates: [],
    },
    // exports
    {
      file: "packages/a/src/Utils.ts",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [
        {
          name: "specialFunc",
          line: 48,
          col: 14,
          pos: 1587,
        },
        {
          name: "uselessFunc",
          line: 50,
          col: 14,
          pos: 1686,
        },
      ],
      types: [],
      enumMembers: {},
      classMembers: {},
      duplicates: [],
    },
    {
      file: "packages/a/src/Weapons.ts",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [{ name: "sheepinator", line: 83, col: 14, pos: 3858 }],
      types: [{ name: "cowinator", line: 75, col: 13, pos: 3686 }],
      enumMembers: {},
      classMembers: {},
      duplicates: [],
    },
    // types
    {
      file: "packages/b/Clank.ts",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [
        { name: "SpecialAgent", line: 7, col: 13, pos: 310 },
        { name: "Zoni", line: 11, col: 13, pos: 407 },
      ],
      enumMembers: {},
      classMembers: {},
      duplicates: [],
    },
    {
      file: "packages/b/Ratchet.ts",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [
        { name: "Lombax", line: 7, col: 13, pos: 310 },
        { name: "Homeworld", line: 11, col: 13, pos: 407 },
      ],
      enumMembers: {},
      classMembers: {},
      duplicates: [],
    },
    // enumMembers
    {
      file: "DrNefarious.ts",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {
        Homeworld: [
          { name: "Magmos", line: 37, col: 5, pos: 1273 },
          { name: "Aquatos", line: 38, col: 5, pos: 1300 },
          { name: "Leviathan", line: 39, col: 5, pos: 1317 },
          { name: "TombliOutpost", line: 40, col: 5, pos: 1317 },
          { name: "Zanifar ", line: 41, col: 5, pos: 1317 },
          { name: "NefariousSpaceStation ", line: 42, col: 5, pos: 1317 },
          { name: "NefariousCity", line: 43, col: 5, pos: 1317 },
          { name: "CorsonV", line: 44, col: 5, pos: 1317 },
        ],
      },
      classMembers: {},
      duplicates: [],
    },
    {
      file: "Sigmund.ts",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {
        Residence: [
          { name: "Viceron", line: 37, col: 5, pos: 1273 },
          { name: "GreatClock", line: 38, col: 5, pos: 1300 },
        ],
        Membership: [
          { name: "ZordoomPrison", line: 37, col: 5, pos: 1273 },
          { name: "GreatClockStaff", line: 38, col: 5, pos: 1300 },
        ],
      },
      classMembers: {},
      duplicates: [],
    },
    // classMembers
    {
      file: "Rivet.ts",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {},
      classMembers: {
        Rivet: [
          { name: "fly", line: 327, col: 9, pos: 12268 },
          { name: "swim", line: 353, col: 3, pos: 12977 },
          { name: "explode", line: 357, col: 3, pos: 13056 },
          { name: "mutate", line: 381, col: 3, pos: 13810 },
          { name: "refineGelatonium ", line: 388, col: 3, pos: 13987 },
        ],
      },
      duplicates: [],
    },
    {
      file: "Qwark.ts",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {},
      classMembers: {
        SaneQwark: [{ name: "rescue", line: 327, col: 9, pos: 12268 }],
        InsaneQwark: [{ name: "destroy", line: 327, col: 9, pos: 12268 }],
      },
      duplicates: [],
    },
    // duplicates
    {
      file: "Lombax.ts",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {},
      classMembers: {},
      duplicates: [[{ name: "Ratchet" }, { name: "default" }]],
    },
    {
      file: "WarBot.ts",
      dependencies: [],
      devDependencies: [],
      optionalPeerDependencies: [],
      unlisted: [],
      binaries: [],
      unresolved: [],
      exports: [],
      types: [],
      enumMembers: {},
      classMembers: {},
      duplicates: [[{ name: "Kit" }, { name: "default" }]],
    },
  ],
};
